// Regenerates src/lib/avatar.ts: a 32x32 phosphor sprite of the profile photo.
// Usage: node scripts/pixelate-avatar.mjs [source-image]
// Steps: crop head and shoulders, downsample, flood-fill the studio background
// out from the edges, then map luminance onto the 5-tone ramp with Bayer dithering.
import { writeFileSync } from "node:fs";
import sharp from "sharp";

const SIZE = 32;
const source = process.argv[2] ?? new URL("../public/images/profile-pic.webp", import.meta.url).pathname;
// head-and-shoulders crop, as fractions of the square source
const CROP = { left: 0.1, top: 0.0, size: 0.84 };
// >1 darkens mid-tones so skin reads as mid-green rather than highlight
const GAMMA = 1.5;
// how far into a band the dither may reach (0 = posterised, 1 = full ordered dither)
const DITHER = 0.45;
const RAMP = ["k", "c", "b", "a", "h", "w"];
const BAYER = [0, 8, 2, 10, 12, 4, 14, 6, 3, 11, 1, 9, 15, 7, 13, 5].map((v) => (v + 0.5) / 16);

const image = sharp(source);
const { width } = await image.metadata();
const px = (fraction) => Math.round(fraction * width);
const { data } = await image
  .extract({ left: px(CROP.left), top: px(CROP.top), width: px(CROP.size), height: px(CROP.size) })
  .resize(SIZE, SIZE, { kernel: "lanczos3" })
  .removeAlpha()
  .raw()
  .toBuffer({ resolveWithObject: true });

const at = (x, y) => [data[(y * SIZE + x) * 3], data[(y * SIZE + x) * 3 + 1], data[(y * SIZE + x) * 3 + 2]];
const luma = ([r, g, b]) => (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
const chroma = ([r, g, b]) => (Math.max(r, g, b) - Math.min(r, g, b)) / 255;
const isBackdrop = (rgb) => luma(rgb) > 0.72 && chroma(rgb) < 0.07;

// flood-fill the backdrop from the top and side edges (the shirt reaches the bottom edge)
const background = new Set();
const queue = [];
for (let i = 0; i < SIZE; i += 1) queue.push([i, 0], [0, i], [SIZE - 1, i]);
while (queue.length) {
  const [x, y] = queue.pop();
  const key = y * SIZE + x;
  if (x < 0 || y < 0 || x >= SIZE || y >= SIZE || background.has(key) || !isBackdrop(at(x, y))) continue;
  background.add(key);
  queue.push([x + 1, y], [x - 1, y], [x, y + 1], [x, y - 1]);
}

// stretch the subject's luminance range so the ramp is fully used
const subject = [];
for (let i = 0; i < SIZE * SIZE; i += 1) if (!background.has(i)) subject.push(luma(at(i % SIZE, Math.floor(i / SIZE))));
subject.sort((a, b) => a - b);
const low = subject[Math.floor(subject.length * 0.03)];
const high = subject[Math.floor(subject.length * 0.97)];

const rows = [];
for (let y = 0; y < SIZE; y += 1) {
  let row = "";
  for (let x = 0; x < SIZE; x += 1) {
    if (background.has(y * SIZE + x)) {
      row += ".";
      continue;
    }
    const t = Math.min(1, Math.max(0, (luma(at(x, y)) - low) / (high - low))) ** GAMMA;
    const level = t * (RAMP.length - 1);
    const base = Math.floor(level);
    const threshold = 0.5 - DITHER / 2 + DITHER * BAYER[(y & 3) * 4 + (x & 3)];
    const step = level - base > threshold ? 1 : 0;
    row += RAMP[Math.min(RAMP.length - 1, base + step)];
  }
  rows.push(row);
}

// rim light: ink pixels touching the backdrop lift one step so dark hair keeps its silhouette
const rimmed = rows.map((row, y) =>
  [...row]
    .map((key, x) => {
      if (key !== "k") return key;
      const edge = [[1, 0], [-1, 0], [0, 1], [0, -1]].some(([dx, dy]) => (rows[y + dy]?.[x + dx] ?? ".") === ".");
      return edge ? "c" : key;
    })
    .join(""),
);
rows.splice(0, rows.length, ...rimmed);

const out = new URL("../src/lib/avatar.ts", import.meta.url);
writeFileSync(
  out,
  `// Generated by scripts/pixelate-avatar.mjs from the profile photo. Do not edit by hand.\n` +
    `export const avatarSprite: string[] = [\n${rows.map((row) => `  "${row}",`).join("\n")}\n];\n`,
);
console.log(rows.join("\n"));
